### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by nouryehia** [sbailouni/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
   - VSCode link should be embedded
   - Account lookup link should be embedded
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
   - headers instead of bolding would make them stand out more
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
   - not counting keystrokes
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
- Great theme and overall look!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by sbailouni** [comment]
Hello, is it possible to get more clarification on what you meant by embedding the links to VS Code and the account lookup site? I’ve embedded both of them using the format [Link] (http://a.com), should we be embedding links differently? 

Also, would this portion correctly address the counting keystrokes requirement? Just want to double check before officially submitting a regrade request on Gradescope. 

![Image](https://user-images.githubusercontent.com/97708686/150928243-2daa4569-e2ac-4c8b-b2ba-e8c1ce2b59ab.png)

Thank you for your time and help! :)

**Comment by nouryehia** [comment]
hello! apologies for the late reply. It seems like links are now embedded correctly in the report! Keystrokes refer to the number of times you tap a key in your keyboard or click the mouse (i.e. typing "hello" takes 5 keystrokes). Seems like you counted the number of lines. However, since I was late to reply and you still counted something, I adjusted the grade anyways!
